test_url = "https://demo.zen-q.com"
prod_url = "http://trade.zen-q.com"

place_order_url = "/API/V2/PlaceOrderAPI.php?"
search_ticker_url = "/API/V2/SearchTickerAPI.php?"
order_list_url = "/api/OrdersListAPI3.php?"
modify_order_url = "/api/ModifyOrderAPI.php?"
cancel_order_url = "/api/ChangeOrderStatusAPI.php?"
user_balances_url = "/API/V2/UserBalancesPortfolio.php?"
login_url = "/API/V2/login.php"
create_api_url = "/API/V2/CustomersAPIManagement/CreateAPIKey.php"
create_sub_acc_url = "/API/Backend/CreateSubAccount.php?"
